name: boorusama
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sliding_up_panel:
    git:
      url: https://github.com/AndroidNils/sliding_up_panel
      ref: body-size
  animations: ^1.1.2
  bloc: ^6.1.0
  bubble_bottom_bar: ^1.2.0
  cached_network_image: ^2.3.3
  carousel_slider: ^2.3.1
  chewie: ^0.9.10
  connectivity: ^2.0.2
  cupertino_icons: ^0.1.3
  dio: ^3.0.10
  dio_cookie_manager: ^1.0.0
  dio_http_cache: ^0.2.11
  equatable: ^1.2.5
  fluro: ^1.7.8
  flushbar: ^1.10.4
  flutter_bloc: ^6.1.0
  flutter_datetime_picker: ^1.4.0
  flutter_downloader: ^1.5.1
  flutter_hooks: ^0.15.0
  flutter_html: ^1.0.2
  flutter_riverpod: ^0.12.1
  flutter_staggered_grid_view: ^0.3.2
  flutter_sticky_header: ^0.5.0
  flutter_tags: ^0.4.9
  freezed_annotation: ^0.12.0
  html: ^0.14.0+3
  http: ^0.12.2
  intl: ^0.16.1
  jiffy: ^3.0.1
  json_annotation: ^3.1.1
  json_serializable: ^3.5.1
  like_button: ^1.0.4
  lottie: ^0.7.0+1
  md2_tab_indicator: ^1.0.2
  meta: ^1.2.3
  modal_bottom_sheet: ^0.2.2
  path: ^1.7.0
  path_provider: ^1.6.18
  permission_handler: ^5.0.1+1
  photo_view: ^0.10.2
  popup_menu: ^1.0.5
  provider: ^4.3.2+2
  pull_to_refresh: ^1.6.2
  retrofit: ^1.3.4+1
  settings_ui: ^0.4.0
  shared_preferences: ^0.5.12+4
  shimmer: ^1.1.2
  sqflite: ^1.3.1+1
  super_tooltip: ^0.9.6
  time: ^1.3.0
  widget_view: ^0.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.4
  freezed: ^0.12.2
  retrofit_generator: ^1.4.1+1

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/animations/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
